name: acme-functors
version: 0.1.0.0
homepage: https://github.com/chris-martin/acme-functors
license: BSD3
license-file: LICENSE
author: Chris Martin
maintainer: ch.martin@gmail.com
copyright: 2017 Chris Martin
github: chris-martin/acme-functors

dependencies:
  - base

library:
  source-dirs: src
  exposed-modules:
    - Acme.Functors

tests:
  test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - phantom-unit-math
