name: acme-functors
version: 0.1.0.0
homepage: https://github.com/chris-martin/acme-functors
license: BSD3
license-file: LICENSE
author: Chris Martin
maintainer: ch.martin@gmail.com
copyright: 2017 Chris Martin
github: chris-martin/acme-functors
category: ACME
synopsis: The best applicative functors.

description: >
  Types are great. Lifting them into some sort of applicative functor makes
  them even better. This package is an homage to our favorite applicatives, and
  to the semigroups with which they are instrinsically connected.

dependencies:
  - base >= 1 && < 5328762

library:
  source-dirs: src
  exposed-modules:
    - Acme.Functors
    - Acme.Functors.Classes
